site_name: My Notes
nav:
  - Python:
    - Virtual Environment: 'virtualenv.md'
    - Pandas: 'pandas.md'
    - Numpy: 'numpy.md'
    - Pytest: 'pytest.md'
    - Logging: 'logging.md'
    - Exception Handling: 'exception_handling.md'
    - OS operations: 'os_operations.md'
  - Frontend:
    - Streamlit: 'streamlit.md'
    - Flask: 'flask.md'
  - MLOps:
    - Git: 'git.md'
    - DVC: 'dvc.md'
    - Docker: 'docker.md'
    - Kubernetes: 'kubernetes.md'
    - Github actions: 'github_actions.md'
    - Azure: 'azure.md'
    - AWS: 'aws.md'
    - GCP: 'gcp.md'
  - Linux:
    - Basics: 'linux_basics.md'
    - Editors: 'linux_editors.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: deep purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/VenkataNaveenK"  target="_blank" rel="noopener">Venkata Naveen K</a>
