site_name: My Notes
nav:
  - Python: 'python.md'
  - Git: 'about.md'
  - Docker: 'about.md'
  - Pytest: 'about.md'
  - Kubernetes: 'about.md'
  - Azure: 'about.md'
  - AWS: 'about.md'
  - GCP: 'about.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
  

