site_name: My Notes
nav:
  - Python:
    - Virtual Environment: python/virtualenv.md
    - Pandas: python/pandas.md
    - Numpy: python/numpy.md
    - Pytest: python/pytest.md
    - Logging: python/logging.md
    - Exception Handling: python/exception_handling.md
    - OS operations: python/os_operations.md
  - Frontend:
    - Streamlit: frontend/streamlit.md
    - Flask: frontend/flask.md
  - MLOps:
    - Git: mlops/git.md
    - DVC: mlops/dvc.md
    - Docker: mlops/docker.md
    - Kubernetes: mlops/kubernetes.md
    - Github actions: mlops/github_actions.md
    - Azure: mlops/azure.md
    - AWS: mlops/aws.md
    - GCP: mlops/gcp.md
    - YAML: mlops/yaml.md
  - Linux:
    - Basics: 
      - Common used commands: linux/basics/common_used_commands.md
      - Utility commands: linux/basics/utility_commands.md
    - Text Editors: 
      - vi/vim: linux/editors/vim_editor.md
      - nano: linux/editors/nano_editor.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: deep purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/VenkataNaveenK"  target="_blank" rel="noopener">Venkata Naveen K</a>
